name: Update TGS API Spec
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  updateSwagger:
    name: Update the TGS API Spec
    runs-on: ubuntu-latest
    steps:
      - name: Setup dotnet 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Clone
        uses: actions/checkout@v4
  
      - name: Apply API update
        run: |
          cd src/Tgstation.Server.ApiUpdater
          dotnet run -- ${{ secrets.GITHUB_TOKEN }} ${{ github.workspace }}
  
      - name: Commit
        continue-on-error: true
        run: |
          git config user.name tgstation-server
          git config user.email tgstation-server@users.noreply.github.com
          git add .
          git commit -m 'Automatic update to latest TGS API'

      - name: Push
        uses: ad-m/github-push-action@master
        if: ${{ success() }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
